apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: nginx
          image: 060027694522.dkr.ecr.us-east-1.amazonaws.com/mi-servidor-web:web
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: php-files
              mountPath: /var/www/html
      volumes:
        - name: php-files
          persistentVolumeClaim:
            claimName: php-pvc
