name: Deploy to EKS

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name mi-cluster --region us-east-1

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f deployment_mysql.yml
          kubectl apply -f deployment_php_fpm.yml
          kubectl apply -f deployment_web.yml
          kubectl apply -f pvc_mysql.yml
          kubectl apply -f pvc.yml
          kubectl apply -f service_mysql.yml
          kubectl apply -f service_php-fpm.yml
          kubectl apply -f service_web.yml

      - name: Verify deployment
        run: |
          kubectl rollout status mysql
          kubectl rollout status php-fpm-deployment
          kubectl rollout status web-deployment
